export const ruRu = {
    delivery: 'Доставка',
    contacts: 'Контакты',
    aboutUs: 'О нас',
    enter: 'Войти',
    exit: 'Выйти',
    whatDoYouWant: 'Что пожелаете?',
    basket: 'Корзина',
    registration: 'Регистрация',
    register: 'Зарегестрироваться',
    authorization: 'Авторизация',
    email: 'Почта',
    password: 'Пароль',
    repeatPassword: 'Повторите пароль',
    loading: 'Загрузка',
    hello: (role: string) => `Привет, ${role}`,
    orders: 'Заказы',
    products: 'Блюда',
    couriers: 'Курьеры',
    add: 'Добавить',
    addNewProduct: 'Добавить новое блюдо',
    addNewProductOfType: (type: string) => `Добавить новое блюдо (${type})`,
    editProductOfType: (type: string) => `Изменить блюдо (${type})`,
    thereAreNoProductsOfType: (type: string) => `Блюда типа "${type}" не найдены`,
    name: 'Название',
    description: 'Описание',
    weight: 'Вес',
    price: 'Цена',
    spiciness: 'Острота',
    ingredients: 'Состав',
    addImage: 'Добавить изображение',
    delete: 'Удалить',
    edit: 'Изменить',
    yes: 'Да',
    no: 'Нет',

    //validations
    pleaseEnterName: 'Введите имя',
    nameCanBeMaxLength: (number: number) => `Имя не может быть более ${number} символов`,
    pleaseEnterPrice: 'Введите цену',
    pleaseEnterWeight: 'Введите вес',
    weightCanBeMaxLength: (number: number) => `Вес не может быть не более ${number} символов`,
    pleaseEnterDescription: 'Введите описание',
    descriptionCanBeMaxLength: (number: number) => `Описание не может быть более ${number} символов`,
    pleaseEnterIngredients: 'Введите состав',
    ingredientsCanBeMaxLength: (number: number) => `Состав не может быть более ${number} символов`,
    pleasePickImage: 'Выберите изображение',
    pleaseEnterEmail: 'Введите почту',
    pleaseEnterValidEmail: 'Введите верную почту',
    pleaseEnterPassword: 'Ввведите пароль',
    pleaseRepeatPassword: 'Введите пароль еще раз',
    passwordsShouldMatch: 'Пароли должны совпадать',
    priceShouldBeMoreThan: (number: number) => `Цена должна быть больше ${number}`,
    priceShouldBeLessThan: (number: number) => `Цена должна быть меньше ${number}`,
    passwordsShouldHaveAtLeastUpper: (number: number) => `Пароль должен иметь ${number} символ(а) в верхнем регистре`,
    passwordsShouldHaveAtLeastLower: (number: number) => `Пароль должен иметь ${number} символ(а) в нижнем регистре`,
    passwordsShouldHaveAtLeastNumber: (number: number) => `Пароль должен иметь ${number} цифру(ы)`,
    passwordsShouldHaveMinLength: (number: number) => `Пароль должен быть ${number} символов в длину`,
    areYouSureYouWantToDeleteName: (name: string) => `Вы уверены, что хотите удалить блюдо "${name}"?`,
    areYouSureYouWantToDelete: `Вы уверены, что хотите удалить это блюдо?`,


    //error
    somethingWentWrong: 'Что-то пошло не так. Попробуйте еще раз',
    userDoesNotExist: 'Пользователь с такой почтой не существует',
    userAlreadyExists: 'Пользователь с такой почтой уже существует',
    wrongPassword: 'Неверный пароль',

    //roles
    manager: 'Менеджер',
    customer: 'Покупатель',
    courier: 'Курьер',

    //product types
    sushi: 'Суши',
    rolls: 'Роллы',
    sets: 'Сеты',
    soups: 'Супы',
    noodles: 'Лапша',
    snacks: 'Закуски',
    drinks: 'Напитки',
    garnish: 'Гарнир',

    //spiciness types
    notSpicy: 'Не острое',
    spicy: 'Острое',
};